version: "3.7"

services: 
  database_dev:
    image: postgres
    container_name: database_dev
    restart: always # para restartar a cada alteracao.
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=adm_db
      - POSTGRES_PASSWORD=senha_db
      - POSTGRES_DB=name_db
    volumes:
      - pgdata:/data/pos
    network_mode: host
  app:
    build: .
    container_name:  Locadora-veiculos
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
    
volumes:
  pgdata:
    driver: local # padrao podendo passar outro caminho
